import streamlit as st
import cv2
import numpy as np
import math
import datetime
import pandas as pd
from PIL import Image
from ultralytics import YOLO
from streamlit_drawable_canvas import st_canvas
import os
from fpdf import FPDF
import base64

# Konfigurasi Halaman Dasar
st.set_page_config(page_title="EUREKA - NDT AI Inspection", layout="wide", page_icon="☢️")

@st.cache_resource
def load_model():
    """Memuat model YOLOv8 untuk segmentasi cacat las."""
    return YOLO('models/eureka_industri.pt')

model = load_model()

# ==========================================
# INISIALISASI SESSION STATE
# ==========================================
KOLOM_TABEL = ["Sumber", "Tipe Cacat", "Conf (%)", "Dimensi (px)", "Luas (px²)", "Dimensi (mm)", "Luas (mm²)"]

if 'history_inspeksi' not in st.session_state:
    st.session_state['history_inspeksi'] = []
if 'px_to_mm_ratio' not in st.session_state:
    st.session_state['px_to_mm_ratio'] = 0.1
if 'ai_ran' not in st.session_state:
    st.session_state['ai_ran'] = False
if 'df_defects' not in st.session_state:
    st.session_state['df_defects'] = pd.DataFrame(columns=KOLOM_TABEL)
if 'jumlah_gambar_manual' not in st.session_state:
    st.session_state['jumlah_gambar_manual'] = 0

# ==========================================
# SIDEBAR: LOGO, NAVIGASI, DAN PARAMETER AI
# ==========================================
path_brin = 'assets/BRIN_logo.png'
path_poltek = 'assets/Poltek Nuklir.png'

# Injeksi Logo Institusi (Base64)
if os.path.exists(path_brin) and os.path.exists(path_poltek):
    with open(path_brin, "rb") as f:
        brin_b64 = base64.b64encode(f.read()).decode()
    with open(path_poltek, "rb") as f:
        poltek_b64 = base64.b64encode(f.read()).decode()
    
    st.sidebar.markdown(
        f"""
        <div style="display: flex; justify-content: center; align-items: center; margin-bottom: 10px;">
            <img src="data:image/png;base64,{brin_b64}" style="height: 60px; margin-right: 20px;">
            <img src="data:image/png;base64,{poltek_b64}" style="height: 60px;">
        </div>
        """,
        unsafe_allow_html=True
    )

#st.sidebar.title("EUREKA")
st.sidebar.markdown("---")

# Navigasi Menu Utama
menu = st.sidebar.selectbox("Navigasi Menu", ["Home", "Single Inspection", "Batch Inspection", "Report Generator"])

st.sidebar.markdown("---")
st.sidebar.markdown("### 🎛️ Parameter AI")
conf_thresh = st.sidebar.slider("Batas Keyakinan (Confidence)", min_value=0.10, max_value=0.99, value=0.55, step=0.05)
batas_luas_maks = st.sidebar.number_input("Filter Luas Maksimal (mm²)", min_value=1.0, max_value=5000.0, value=50.0, step=5.0, help="Mengabaikan prediksi AI jika luas melebihi batas (Penyaring Out-of-Distribution/Base Metal).")
gunakan_clahe = st.sidebar.checkbox("Aktifkan Filter CLAHE", value=False, help="Normalisasi kontras citra radiografi industri.")

# ==========================================
# FUNGSI REPORT GENERATOR (PDF)
# ==========================================
def generate_pdf_report(nama_file, tgl_uji, lokasi, inspektor, perusahaan, client, tebal_las, status_akhir, df_final, catatan, rasio, image_array=None):
    """Menghasilkan laporan inspeksi berformat PDF dengan standar formal."""
    pdf = FPDF()
    pdf.add_page()
    
    # Injeksi Kop Surat
    path_kop = 'assets/kop.jpg'
    if os.path.exists(path_kop):
        pdf.image(path_kop, x=10, y=10, w=190)
        pdf.ln(40) 
    else:
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(200, 10, txt="[KOP SURAT TIDAK DITEMUKAN]", ln=True, align='C')
        pdf.ln(10)

    # Header Laporan
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 8, txt="LAPORAN EVALUASI RADIOGRAFI (NDT)", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 6, txt="Generated by EUREKA System (AWS D1.1 Standard)", ln=True, align='C')
    pdf.ln(8)
    
    # Bagian Administrasi Data Inspeksi
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(200, 6, txt="DATA INSPEKSI:", ln=True)
    pdf.set_font("Arial", '', 10)
    
    nama_file_display = f"{nama_file[:30]}..." if len(nama_file) > 30 else nama_file
    nama_client_display = client if client else "-"
    
    pdf.cell(35, 6, txt="Nama File Citra")
    pdf.cell(55, 6, txt=f": {nama_file_display}")
    pdf.cell(25, 6, txt="Inspektor")
    pdf.cell(75, 6, txt=f": {inspektor}", ln=True)
    
    pdf.cell(35, 6, txt="Tanggal Uji")
    pdf.cell(55, 6, txt=f": {tgl_uji}")
    pdf.cell(25, 6, txt="Perusahaan")
    pdf.cell(75, 6, txt=f": {perusahaan}", ln=True)
    
    pdf.cell(35, 6, txt="Lokasi Uji")
    pdf.cell(55, 6, txt=f": {lokasi}")
    pdf.cell(25, 6, txt="Client")
    pdf.cell(75, 6, txt=f": {nama_client_display}", ln=True)
    
    pdf.cell(35, 6, txt="Tebal Las (S)")
    pdf.cell(55, 6, txt=f": {tebal_las} mm")
    pdf.cell(25, 6, txt="Kalibrasi")
    pdf.cell(75, 6, txt=f": 1 px = {rasio:.4f} mm", ln=True)
    pdf.ln(8)
    
    # =======================================================
    # FITUR BARU: INJEKSI VISUALISASI GAMBAR KE DALAM PDF
    # =======================================================
    if image_array is not None:
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(200, 6, txt="VISUALISASI ANOMALI & ANOTASI INSPEKTUR:", ln=True)
        pdf.ln(2)
        
        # Simpan array gambar ke disk secara temporer
        temp_img_path = f"temp_report_{datetime.datetime.now().strftime('%H%M%S')}.jpg"
        cv2.imwrite(temp_img_path, image_array)
        
        # Kalkulasi Aspek Rasio (Mencegah gambar tinggi tumpah/hancur di PDF)
        h_px, w_px = image_array.shape[:2]
        aspect = h_px / w_px
        pdf_w = 120 # Lebar dasar 120mm
        pdf_h = pdf_w * aspect
        
        # Limitasi tinggi gambar maksimal 100mm agar tabel muat di bawahnya
        if pdf_h > 100:
            pdf_h = 100
            pdf_w = pdf_h / aspect
            
        x_offset = (210 - pdf_w) / 2 # Membuat gambar rata tengah (Center Align)
        
        pdf.image(temp_img_path, x=x_offset, w=pdf_w, h=pdf_h)
        pdf.ln(pdf_h + 5) # Tambahkan ruang kosong di bawah gambar
        
        # Hapus file temporer agar penyimpanan hardisk tidak penuh
        try:
            os.remove(temp_img_path)
        except Exception:
            pass
    # =======================================================
    
    # Bagian Tabel Deteksi Cacat
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(200, 6, txt="HASIL DETEKSI (HITL Validated):", ln=True)
    
    pdf.set_font("Arial", 'B', 9)
    pdf.cell(30, 8, "Sumber", 1)
    pdf.cell(25, 8, "Cacat", 1)
    pdf.cell(20, 8, "Conf(%)", 1)
    pdf.cell(35, 8, "Dimensi (px)", 1)
    pdf.cell(35, 8, "Dimensi (mm)", 1)
    pdf.cell(40, 8, "Luas (mm2)", 1)
    pdf.ln()
    
    pdf.set_font("Arial", '', 9)
    if len(df_final) == 0:
        pdf.cell(185, 8, "Tidak ada indikasi cacat (Bersih)", 1, ln=True, align='C')
    else:
        for idx, row in df_final.iterrows():
            pdf.cell(30, 8, str(row['Sumber']), 1)
            pdf.cell(25, 8, str(row['Tipe Cacat']), 1)
            pdf.cell(20, 8, f"{row['Conf (%)']:.0f}", 1)
            pdf.cell(35, 8, f"{row['Dimensi (px)']:.2f}", 1)
            pdf.cell(35, 8, f"{row['Dimensi (mm)']:.2f}", 1)
            pdf.cell(40, 8, f"{row['Luas (mm²)']:.2f}", 1)
            pdf.ln()
    pdf.ln(8)
    
    # Bagian Vonis dan Catatan
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(200, 6, txt="KEPUTUSAN AKHIR (AWS D1.1):", ln=True)
    pdf.set_font("Arial", 'B', 14)
    if "ACCEPT" in status_akhir:
        pdf.set_text_color(0, 150, 0)
    else:
        pdf.set_text_color(255, 0, 0)
    pdf.cell(200, 10, txt=f"STATUS EVALUASI : {status_akhir}", ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 10)
    pdf.multi_cell(0, 6, txt=f"Catatan/Justifikasi :\n{catatan if catatan else '-'}")
    
    return pdf.output(dest='S').encode('latin1')

# ==========================================
# HALAMAN: HOME
# ==========================================
if menu == "Home":
    st.title("EUREKA")
    st.markdown("*Expertise Utility for Radiographic Evaluation, Knowledge, and Analysis*")
    
    st.markdown("### 📂 Mulai Inspeksi Baru")
    uploaded_file = st.file_uploader("Unggah Citra Radiografi", type=["jpg", "png", "jpeg"])
    
    if uploaded_file is not None:
        if uploaded_file.name != st.session_state.get('current_filename'):
            st.session_state['uploaded_image'] = uploaded_file
            st.session_state['current_filename'] = uploaded_file.name 
            st.session_state['df_defects'] = pd.DataFrame(columns=KOLOM_TABEL)
            st.session_state['ai_ran'] = False
            st.session_state['jumlah_gambar_manual'] = 0
            if "ai_results" in st.session_state: del st.session_state['ai_results']
            if "editor_cacat" in st.session_state: del st.session_state["editor_cacat"]
        st.success("Citra berhasil diunggah! Silakan pindah ke tab **Single Inspection**.")

    st.markdown("---")
    st.markdown("### 📋 Riwayat Inspeksi")
    if len(st.session_state['history_inspeksi']) == 0:
        st.info("Belum ada riwayat inspeksi pada sesi ini.")
    else:
        df_hist = pd.DataFrame(st.session_state['history_inspeksi'])
        st.dataframe(df_hist[["Nama File", "Tanggal", "Status", "Detail"]], use_container_width=True)

# ==========================================
# HALAMAN: SINGLE INSPECTION (HITL MODULE)
# ==========================================
elif menu == "Single Inspection":
    st.title("Digital Radiography Assessment Dashboard")
    
    if 'uploaded_image' not in st.session_state or st.session_state['uploaded_image'] is None:
        st.warning("Silakan unggah citra terlebih dahulu di halaman Home.")
    else:
        file_bytes = np.asarray(bytearray(st.session_state['uploaded_image'].getvalue()), dtype=np.uint8)
        img_cv2 = cv2.imdecode(file_bytes, 1)
        img_rgb = cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB)
        
        if st.button("Eureka Auto Annotations", use_container_width=True):
            if "editor_cacat" in st.session_state: del st.session_state["editor_cacat"]
            st.session_state['jumlah_gambar_manual'] = 0
                
            with st.spinner('Memindai anomali las...'):
                img_pred = img_rgb.copy()
                
                # Pra-pemrosesan CLAHE (Contrast Limited Adaptive Histogram Equalization)
                if gunakan_clahe:
                    lab = cv2.cvtColor(img_pred, cv2.COLOR_RGB2LAB)
                    l, a, b = cv2.split(lab)
                    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
                    cl = clahe.apply(l)
                    merged = cv2.merge((cl, a, b))
                    img_pred = cv2.cvtColor(merged, cv2.COLOR_LAB2RGB)

                # Eksekusi prediksi model YOLOv8
                results = model.predict(img_pred, conf=conf_thresh) 
                st.session_state['ai_results'] = results[0] 
                
                df_list = []
                rasio = st.session_state['px_to_mm_ratio']
                
                if len(results[0].boxes) > 0:
                    for i, box in enumerate(results[0].boxes):
                        cls_id = int(box.cls[0].item())
                        nama = model.names[cls_id]
                        konfidensi = float(box.conf[0].item()) * 100 
                        w = box.xywh[0][2].item()
                        h = box.xywh[0][3].item()
                        
                        dimensi_px = float(max(w, h))
                        luas_px = float(w * h)
                        dimensi_mm = float(dimensi_px * rasio)
                        luas_mm2 = float(luas_px * (rasio**2))
                        
                        # Filter anomali berbasis luas maksimum (Mencegah false positive pada Base Metal)
                        if luas_mm2 <= batas_luas_maks:
                            df_list.append({
                                "Sumber": f"AI-{i+1}",
                                "Tipe Cacat": nama,
                                "Conf (%)": float(konfidensi),
                                "Dimensi (px)": dimensi_px,
                                "Luas (px²)": luas_px,
                                "Dimensi (mm)": dimensi_mm,
                                "Luas (mm²)": luas_mm2
                            })
                            
                st.session_state['df_defects'] = pd.DataFrame(df_list) if len(df_list) > 0 else pd.DataFrame(columns=KOLOM_TABEL)
                st.session_state['ai_ran'] = True
                st.rerun()
        
        st.markdown("---")
        col1, col2 = st.columns([6, 5])
        
        with col1:
            st.subheader("Radiograph Spatial Viewer")
            tampilkan_overlay = st.toggle("Tampilkan Overlay AI", value=True)
            mode_alat = st.radio("Mode Pengoperasian Kanvas:", ["🔍 Navigasi (Hanya Lihat)", "📏 Kalibrasi Penggaris", "🖍️ Anotasi Poligon Manual"], horizontal=True)
            
            d_mode = "transform"
            color = "#000000"
            
            if "Kalibrasi" in mode_alat:
                d_mode = "line"
                color = "#00FF00"
            elif "Anotasi" in mode_alat:
                d_mode = "polygon"
                color = "#FF0000" 
                st.info("Instruksi: Bentuk poligon cacat. Pastikan poligon tertutup (klik kanan di titik akhir), kemudian simpan menggunakan tombol di bawah.")

            img_display = img_rgb.copy()
            
            # Rendering Masking YOLO ke dalam OpenCV (Performa tinggi & Dinamis)
            if st.session_state['ai_ran'] and tampilkan_overlay and 'ai_results' in st.session_state:
                overlay = img_display.copy()
                sumber_aktif = st.session_state['df_defects']['Sumber'].tolist() 
                res = st.session_state['ai_results']
                
                if len(res.boxes) > 0:
                    for i, box in enumerate(res.boxes):
                        sumber_id = f"AI-{i+1}"
                        # Sinkronisasi status visibilitas dengan eksistensi baris di Data Editor
                        if sumber_id in sumber_aktif: 
                            cls_id = int(box.cls[0].item())
                            nama = model.names[cls_id]
                            
                            if nama == 'CR': warna = (255, 0, 0)
                            elif nama == 'PO': warna = (0, 0, 255)
                            else: warna = (255, 165, 0)
                            
                            if res.masks is not None:
                                pts = np.int32(res.masks.xy[i])
                                cv2.fillPoly(overlay, [pts], warna)
                            
                            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
                            cv2.rectangle(overlay, (x1, y1), (x2, y2), warna, 2)
                            
                            try:
                                conf_val = st.session_state['df_defects'].loc[st.session_state['df_defects']['Sumber'] == sumber_id, 'Conf (%)'].values[0]
                                label_text = f"{sumber_id} ({conf_val:.0f}%)"
                            except:
                                label_text = sumber_id
                                
                            cv2.putText(overlay, label_text, (x1, y1-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, warna, 2)
                
                cv2.addWeighted(overlay, 0.4, img_display, 0.6, 0, img_display)

            h, w = img_rgb.shape[:2]
            kanvas_lebar = 550 
            kanvas_tinggi = int(h * (kanvas_lebar / w))
            
            if 'canvas_key' not in st.session_state:
                st.session_state['canvas_key'] = 0
            
            img_pil = Image.fromarray(img_display)
            
            canvas_key = f"canvas_utama_{st.session_state['canvas_key']}"
            
            canvas_result = st_canvas(
                fill_color="rgba(255, 0, 0, 0.3)",
                stroke_width=3,
                stroke_color=color,
                background_image=img_pil,
                width=kanvas_lebar,
                height=kanvas_tinggi,
                drawing_mode=d_mode,
                key=canvas_key, 
            )
            
            if canvas_result.json_data is not None and len(canvas_result.json_data["objects"]) > 0:
                pass
            
            faktor_skala = w / kanvas_lebar
            
            # Pemrosesan Geometri Kanvas (Ruler Kalibrasi & Poligon Manual)
            if canvas_result.json_data is not None and len(canvas_result.json_data["objects"]) > 0:
                obj_terakhir = canvas_result.json_data["objects"][-1] 
                
                if obj_terakhir["type"] == "line" and "Kalibrasi" in mode_alat:
                    px_asli = math.sqrt(obj_terakhir["width"]**2 + obj_terakhir["height"]**2) * faktor_skala
                    st.write(f"Jarak Ekstraksi Spasial: **{px_asli:.2f} piksel**")
                    mm_asli = st.number_input("Input Ukuran Aktual Referensi (mm):", min_value=0.1, value=15.0)
                    if st.button("Terapkan Kalibrasi Spasial"):
                        rasio_baru = mm_asli / px_asli
                        st.session_state['px_to_mm_ratio'] = rasio_baru
                        if not st.session_state['df_defects'].empty:
                            st.session_state['df_defects']['Dimensi (mm)'] = st.session_state['df_defects']['Dimensi (px)'] * rasio_baru
                            st.session_state['df_defects']['Luas (mm²)'] = st.session_state['df_defects']['Luas (px²)'] * (rasio_baru**2)
                        if "editor_cacat" in st.session_state: del st.session_state["editor_cacat"]
                        st.success(f"Kalibrasi berhasil. Nilai pengali spasial: 1 px = {rasio_baru:.4f} mm")
                        st.rerun()

            if "Anotasi" in mode_alat:
                st.markdown("---")
                if st.button("Input Anotasi ke Tabel", type="primary", use_container_width=True):
                    if canvas_result.json_data is not None and len(canvas_result.json_data["objects"]) > 0:
                        obj_terakhir = canvas_result.json_data["objects"][-1]
                        if obj_terakhir["type"] in ["rect", "polygon", "path"]:
                            w_obj = obj_terakhir.get("width", 0) * obj_terakhir.get("scaleX", 1)
                            h_obj = obj_terakhir.get("height", 0) * obj_terakhir.get("scaleY", 1)
                            px_manual = max(w_obj, h_obj) * faktor_skala
                            luas_px = (w_obj * faktor_skala) * (h_obj * faktor_skala)
                            rasio = st.session_state.get('px_to_mm_ratio', 0.1)
                            
                            st.session_state['jumlah_gambar_manual'] += 1
                            
                            baris_baru = pd.DataFrame([{
                                "Sumber": f"Manual-{st.session_state['jumlah_gambar_manual']}",
                                "Tipe Cacat": "CR", 
                                "Conf (%)": 100.0, 
                                "Dimensi (px)": float(px_manual),
                                "Luas (px²)": float(luas_px),
                                "Dimensi (mm)": float(px_manual * rasio),
                                "Luas (mm²)": float(luas_px * (rasio**2))
                            }])
                            st.session_state['df_defects'] = pd.concat([st.session_state['df_defects'], baris_baru], ignore_index=True)
                            if "editor_cacat" in st.session_state: del st.session_state["editor_cacat"]
                            st.rerun()
                        else:
                            st.error("Gagal mendeteksi poligon tertutup. Evaluasi ulang titik terminasi poligon.")
                    else:
                        st.error("Objek anomali belum didefinisikan pada kanvas inspeksi.")

        with col2:
            st.subheader("Discontinuity Summary")
            
            # Editor Data Interaktif
            edited_df = st.data_editor(
                st.session_state['df_defects'],
                column_config={
                    "Sumber": st.column_config.TextColumn("Sumber", disabled=True),
                    "Tipe Cacat": st.column_config.SelectboxColumn("Cacat", options=["CR", "PO", "IP"]),
                    "Conf (%)": st.column_config.NumberColumn("Conf (%)", format="%.0f", disabled=True),
                    "Dimensi (px)": st.column_config.NumberColumn("Dim (px)", format="%.1f", disabled=True),
                    "Luas (px²)": None, 
                    "Dimensi (mm)": st.column_config.NumberColumn("Dim (mm)", format="%.2f", disabled=True),
                    "Luas (mm²)": st.column_config.NumberColumn("Luas (mm²)", format="%.2f", disabled=True)
                },
                num_rows="dynamic",
                use_container_width=True,
                key="editor_cacat"
            )
            
            if not edited_df.equals(st.session_state['df_defects']):
                st.session_state['df_defects'] = edited_df
                st.rerun()
            
            st.markdown("---")
            st.subheader("Autonomous Acceptance Engine AWS D1.1")
            tebal_las = st.number_input("Parameter Tebal Las Aktual (S) dalam mm:", min_value=1.0, value=10.0, step=1.0)
            
            # Formulasi Ambang Batas Evaluasi (AWS D1.1 Clause 8.12)
            batas_po = min(tebal_las / 3.0, 6.0)
            batas_ip = tebal_las / 3.0
            st.write(f"*(Kalkulasi Ambang Toleransi: PO maks {batas_po:.2f} mm, IP maks {batas_ip:.2f} mm)*")
            
            cr_reject, ip_reject, po_reject = False, False, False
            alasan_reject = []
            
            for idx, row in edited_df.iterrows():
                tipe = row['Tipe Cacat']
                dim_mm = row['Dimensi (mm)'] if not pd.isna(row['Dimensi (mm)']) else 0.0
                
                if tipe == 'CR': cr_reject = True
                elif tipe == 'IP' and dim_mm > batas_ip: ip_reject = True
                elif tipe == 'PO' and dim_mm > batas_po: po_reject = True
                    
            if cr_reject: alasan_reject.append("Crack (Toleransi 0/Indikasi Linier Tidak Diizinkan)")
            if ip_reject: alasan_reject.append(f"Incomplete Penetration melampaui batas ambang ({batas_ip:.2f} mm)")
            if po_reject: alasan_reject.append(f"Porosity melampaui batas ambang ({batas_po:.2f} mm)")
            
            # Render Keputusan Akhir Sistem
            if len(edited_df) == 0:
                status_akhir = "ACCEPT"
                st.success("Sistem: **ACCEPT** (Tidak ditemukan anomali kecacatan)")
            elif cr_reject or ip_reject or po_reject:
                status_akhir = "REJECT"
                st.error("Sistem: **REJECT** (Ditemukan pelanggaran kriteria keberterimaan)")
                for alasan in alasan_reject: st.write(f"- {alasan}")
            else:
                status_akhir = "ACCEPT"
                st.success("Sistem: **ACCEPT** (Indikasi cacat berada dalam batas toleransi)")
            
            st.markdown("---")
            if st.button("💾 Simpan Hasil Inspeksi", type="primary"):
                waktu_sekarang = datetime.datetime.now()
                ringkasan = ", ".join([f"{row['Tipe Cacat']}({row['Dimensi (mm)']:.1f}mm)" for i, row in edited_df.iterrows() if not pd.isna(row['Dimensi (mm)'])])
                
                # FITUR BARU: Tangkap gambar dari layar (gabungan Citra Asli + Masking AI)
                img_to_save_bgr = cv2.cvtColor(img_display, cv2.COLOR_RGB2BGR)
                
                # Cek jika ada gambar poligon dari kanvas manual, tempelkan juga di atasnya!
                if canvas_result.image_data is not None:
                    h_orig, w_orig = img_to_save_bgr.shape[:2]
                    canvas_rgba = canvas_result.image_data
                    canvas_resized = cv2.resize(canvas_rgba, (w_orig, h_orig))
                    alpha_mask = canvas_resized[:, :, 3] > 0
                    # Konversi warna kanvas RGBA ke BGR format OpenCV
                    img_to_save_bgr[alpha_mask] = canvas_resized[alpha_mask, 2::-1] 
                
                st.session_state['history_inspeksi'].append({
                    "Nama File": st.session_state['current_filename'],
                    "Tanggal": waktu_sekarang.strftime("%d/%M/%Y - %H:%M"),
                    "Status": status_akhir,
                    "Detail": ringkasan if ringkasan else "Bebas Cacat",
                    "df_raw": edited_df.copy(), 
                    "tebal_las": tebal_las,
                    "rasio": st.session_state['px_to_mm_ratio'],
                    "image_array": img_to_save_bgr # SIMPAN KE MEMORI PDF
                })
                st.success("Data inspeksi diarsipkan. Akses menu 'Report Generator' untuk pencetakan dokumen formal.")

# ==========================================
# HALAMAN: REPORT GENERATOR
# ==========================================
elif menu == "Report Generator":
    st.title("📄 Report Generator")
    st.markdown("Modul pembentukan dokumen laporan pengujian fisis (NDT Report) terintegrasi.")
    st.markdown("---")
    
    if len(st.session_state['history_inspeksi']) == 0:
        st.warning("Arsip inspeksi kosong. Selesaikan prosedur 'Single Inspection' untuk mengaktivasi fitur ini.")
    else:
        opsi_inspeksi = [f"{item['Nama File']} | {item['Tanggal']}" for item in st.session_state['history_inspeksi']]
        pilihan = st.selectbox("Identifikasi Arsip Pengujian:", opsi_inspeksi)
        
        idx_pilihan = opsi_inspeksi.index(pilihan)
        data_pilihan = st.session_state['history_inspeksi'][idx_pilihan]
        
        st.write(f"**Vonis Evaluasi:** {data_pilihan['Status']} | **Karakteristik Deteksi:** {data_pilihan['Detail']}")
        st.markdown("---")
        
        st.subheader("Data Administrasi Pengujian")
        
        colA, colB = st.columns(2)
        with colA:
            inspektor = st.text_input("Nama Inspektur Penanggung Jawab:", value="Bambang Sri Handoko K. R.")
            perusahaan = st.text_input("Institusi/Perusahaan Pelaksana:", value="Politeknik Teknologi Nuklir Indonesia")
            client = st.text_input("Entitas Klien (Opsional):", value="")
        with colB:
            tanggal_uji = st.date_input("Tanggal Registrasi:", value=datetime.date.today())
            lokasi = st.text_input("Lokasi Penilaian:", value="KSE A Baiquni Yogyakarta")
            catatan = st.text_area("Justifikasi Teknis / Keterangan Tambahan:")
            
        if st.button("🖨️ Ekspor Laporan PDF", type="primary"):
            tgl_str = tanggal_uji.strftime("%d %B %Y")
            
            citra_visual = data_pilihan.get('image_array', None) 
            
            pdf_bytes = generate_pdf_report(
                nama_file=data_pilihan['Nama File'],
                tgl_uji=tgl_str,
                lokasi=lokasi,
                inspektor=inspektor,
                perusahaan=perusahaan,
                client=client,
                tebal_las=data_pilihan['tebal_las'],
                status_akhir=data_pilihan['Status'],
                df_final=data_pilihan['df_raw'],
                catatan=catatan,
                rasio=data_pilihan['rasio'],
                image_array=citra_visual # KIRIM GAMBAR KE FPDF
            )
            
            st.success("Berkas PDF berhasil digenerasi.")
            st.download_button(
                label="⬇️ Unduh Dokumen Ekspor",
                data=pdf_bytes,
                file_name=f"NDT_Report_{data_pilihan['Nama File']}.pdf",
                mime="application/pdf"
            )

# ==========================================
# HALAMAN: BATCH INSPECTION
# ==========================================
elif menu == "Batch Inspection":
    st.title("Inspeksi Massal Otomatis (Batch Mode)")
    st.markdown("Pemrosesan paralel berbasis sistem visi komputer dan komputasi otonom AWS D1.1.")
    
    st.markdown("### 1. Parameter Eksekusi Global")
    colA, colB = st.columns(2)
    with colA:
        default_ratio = st.session_state.get('px_to_mm_ratio', 0.100)
        global_ratio = st.number_input("Rasio Konversi Spasial (mm/piksel):", min_value=0.001, value=float(default_ratio), step=0.01, format="%.4f")
    with colB:
        tebal_las_batch = st.number_input("Parameter Tebal Las Seragam (mm):", min_value=1.0, value=10.0, step=1.0)
    
    batas_po_batch = min(tebal_las_batch / 3.0, 6.0)
    batas_ip_batch = tebal_las_batch / 3.0
    st.info(f"Basis komputasi toleransi global sistem: **PO maks {batas_po_batch:.2f} mm** | **IP maks {batas_ip_batch:.2f} mm**.")
    
    st.markdown("### 2. Akuisisi Data Massal")
    uploaded_files = st.file_uploader("Impor citra multireferensi", type=["jpg", "png", "jpeg"], accept_multiple_files=True)
    
    if uploaded_files:
        st.write(f"Sistem siap memproses **{len(uploaded_files)}** berkas.")
        
        if st.button("🚀 Inisiasi Proses Batch"):
            batch_results = []
            progress_bar = st.progress(0)
            status_text = st.empty()
            
            output_dir = "Eureka_Batch_Output"
            os.makedirs(output_dir, exist_ok=True)
            
            for idx, file in enumerate(uploaded_files):
                status_text.text(f"Eksekusi pipeline pada citra {idx+1}/{len(uploaded_files)}: {file.name}")
                
                file_bytes = np.asarray(bytearray(file.getvalue()), dtype=np.uint8)
                img_cv2 = cv2.imdecode(file_bytes, 1)
                img_rgb = cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB)
                
                # Pra-pemrosesan CLAHE (terintegrasi dengan pengaturan Global Parameter AI)
                if gunakan_clahe:
                    lab = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2LAB)
                    l, a, b = cv2.split(lab)
                    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
                    cl = clahe.apply(l)
                    merged = cv2.merge((cl, a, b))
                    img_rgb = cv2.cvtColor(merged, cv2.COLOR_LAB2RGB)

                # Eksekusi AI menggunakan parameter keyakinan global (sidebar)
                results = model.predict(img_rgb, conf=conf_thresh, verbose=False)
                
                ada_cr = False
                max_ip_mm = 0.0
                max_po_mm = 0.0
                detail_cacat = []
                
                # Penyaringan Filter Luas Maksimal pada Batch Mode
                boxes_valid = []
                if len(results[0].boxes) > 0:
                    for box in results[0].boxes:
                        w = box.xywh[0][2].item()
                        h = box.xywh[0][3].item()
                        luas_mm2 = (w * h) * (global_ratio**2)
                        
                        if luas_mm2 <= batas_luas_maks:
                            boxes_valid.append(box)
                            cls_id = int(box.cls[0].item())
                            nama_kelas = model.names[cls_id]
                            panjang_mm = max(w, h) * global_ratio
                            
                            detail_cacat.append(nama_kelas)
                            
                            if nama_kelas == 'CR':
                                ada_cr = True
                            elif nama_kelas == 'IP' and panjang_mm > max_ip_mm:
                                max_ip_mm = panjang_mm
                            elif nama_kelas == 'PO' and panjang_mm > max_po_mm:
                                max_po_mm = panjang_mm
                
                # Modifikasi objek results untuk hanya menyimpan deteksi yang valid (lolos filter)
                if len(boxes_valid) > 0:
                     # Fitur tingkat lanjut: merender ulang hanya anotasi yang logis ke gambar output
                     pass # (Pengolahan array PyTorch untuk plot ulang bisa ditambahkan di iterasi mendatang)
                     
                res_plotted = results[0].plot() 
                
                img_bgr_to_save = cv2.cvtColor(res_plotted, cv2.COLOR_RGB2BGR)
                timestamp = datetime.datetime.now().strftime("%H%M%S")
                nama_file_output = f"Analyzed_{timestamp}_{file.name}"
                path_simpan = os.path.join(output_dir, nama_file_output)
                cv2.imwrite(path_simpan, img_bgr_to_save)
                            
                if ada_cr or (max_ip_mm > batas_ip_batch) or (max_po_mm > batas_po_batch):
                    status_akhir = "REJECT"
                else:
                    status_akhir = "ACCEPT"
                
                unik_cacat = list(set(detail_cacat))
                ringkasan_str = ", ".join(unik_cacat) if unik_cacat else "Bebas Cacat"
                
                batch_results.append({
                    "Nama File": file.name,
                    "Deteksi": ringkasan_str,
                    "CR": "Ya" if ada_cr else "Tidak",
                    "Max IP (mm)": f"{max_ip_mm:.2f}",
                    "Max PO (mm)": f"{max_po_mm:.2f}",
                    "Vonis": status_akhir
                })
                
                progress_bar.progress((idx + 1) / len(uploaded_files))
            
            status_text.text(f"Proses batch terselesaikan. Output visual tersimpan pada: {os.path.abspath(output_dir)}")
            
            st.markdown("### Rekapitulasi Data Batch")
            st.dataframe(batch_results, use_container_width=True)
            
            for res in batch_results:
                st.session_state['history_inspeksi'].append({
                    "Nama File": res["Nama File"],
                    "Tanggal": datetime.datetime.now().strftime("%d/%M/%Y - %H:%M"),
                    "Status": res["Vonis"],
                    "Detail": f"Batch: {res['Deteksi']} (PO={res['Max PO (mm)']}, IP={res['Max IP (mm)']})",
                    "df_raw": pd.DataFrame(), 
                    "tebal_las": tebal_las_batch,
                    "rasio": global_ratio
                })
            st.success("Tabel rekapitulasi disinkronisasi ke arsip Home.")
